services:
  mysql:
    image: mysql:8.0
    container_name: portal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal_db
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  localstack:
    image: localstack/localstack:3.0
    container_name: portal-localstack
    restart: unless-stopped
    environment:
      SERVICES: lambda
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./lambda:/lambda-src
      - ./localstack-init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: .
    container_name: portal-backend
    restart: unless-stopped
    depends_on:
      - mysql
      - localstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portal_db
      SPRING_DATASOURCE_USERNAME: portal_user
      SPRING_DATASOURCE_PASSWORD: portal_pass
      APP_AWS_LAMBDA_ENDPOINT: http://localstack:4566
      APP_AWS_ACCESS_KEY: test
      APP_AWS_SECRET_KEY: test
    ports:
      - "8080:8080"

volumes:
  mysql_data: